name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Trigger Jenkins deployment
      env:
        JENKINS_USER: ${{ secrets.JENKINS_USER }}
        JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
      run: |
        curl -u "$JENKINS_USER:$JENKINS_API_TOKEN" \
        -X POST "http://168.131.223.227:8080/job/your-job-name/build"
