name: CD - Jenkins 배포 트리거

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  deploy:
    if: contains(github.event.pull_request.labels.*.name, 'build-full')
    runs-on: ubuntu-latest
    steps:
      - name: Jenkins 트리거 실행
        uses: appleboy/jenkins-action@master
        with:
          url: ${{ secrets.JENKINS_URL }}
          user: jnu
          token: ${{ secrets.JENKINS_API_TOKEN }}
          job: cicd-test
